### ISSUE TITLE
Revive this project

### ISSUE THREAD

**Issue by devingray** [Say-Their-Name/say-their-names-api#81]
Hi, I am the original developer that built this API. I can see that the frontend is not longer available and am unsure about the ios and android apps. 

Is the slack channel still alive? Can someone invite me? I would like to redo this and bring it back. 

cc @hybridcattt

**Comment by hybridcattt** [comment]
Hi Devin! 
Glad to have you back 👋 🙂 Let me give you an overview of the current status: 

The iOS app is still live, the API is also live. It's been redeployed to another Digital Ocean droplet. I have access to all related accounts. We couldn't get access to the original Digital Ocean space that hosted the images, so a lot of records are missing images - we recovered them from an earlier archive. To cut cost, images are statically hosted on Netlify, deployed from [this GitHub repo](https://github.com/Say-Their-Name/images).

The website is down indeed. The original domain saytheirnames.io expired and we couldn't reach you to transfer it like we did earlier with the domain the API lives on. We didn't see the value to deploy to another domain, since all links would stop working anyway. 

Right now it'd be great if we could:
- move all project domains under one GoDaddy account 
- recover missing images from the original Digital Ocean space
- redeploy the website to saytheirnames.io (if we can recover it)
- consider zero-cost options for the API

I'll gladly share access and give you a walkthrough of the changes in the project since you dropped off. 

Here's the link to join the slack: https://bit.ly/join-our-saytheirnames-slack

You can DM me there or send me an email to marina@hybridcattt.com to arrange the practicalities.
